version: '3.8'

services:
  app:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./:/usr/src/
    ports:
      - 8080:8080
    env_file:
      - ./.env
  db:
    image: postgres:13.0-alpine
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER=berkatil
        - POSTGRES_PASSWORD=123
        - POSTGRES_DB=berk
volumes:
    postgres_data:



      
