name: Django CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
  workflow_dispatch:
  
jobs:
  
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: test
      SQL_DATABASE: sports_platform
      SQL_USER: postgres
      SQL_PASSWORD: postgres
      SQL_HOST: 127.0.0.1
      SQL_PORT: 5432
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    services:
      postgres:
        image: postgres:13.0-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sports_platform
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
          
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: back-end/sports_platform
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      working-directory: back-end/sports_platform
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Run Tests
      working-directory: back-end/sports_platform
      run: |
        python manage.py test
